# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d28a40970e793032c3c3a8caf924d4c1cb737001bb5b0a300dca75521b20a7aa5a7639a7b10fe421aade0fa1b0a6ed4e147f2f7ca340c8195b09ca45b05d36bc

test:
  secret_key_base: ed51fa9c4f21dddfc079ddb207ee184b0459f81b583d5a76cb6e895d198884a9e56c9109e608345f1cacd938fb9c2fe3a7d4ef407dd9192bef57526509538fcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
